data:
    dataset: "human36m"
    dataset_path: "./data/data_3d_h36m.npz"
    dataset_path_train_2d: "./data/data_2d_h36m_gt_gmm.npz"
    dataset_path_test_2d: "./data/data_2d_h36m_gt_gmm.npz"
    num_joints: 17
    num_workers: 32

model:
    hid_dim: 96
    emd_dim: 96
    coords_dim: [5,5]
    num_layer: 5
    n_head: 4
    dropout: 0.25
    n_pts: 17
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True
    var_type: fixedsmall

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.001
    num_diffusion_timesteps: 51

training:
    batch_size: 1024
    n_epochs: 80
    n_iters: 5000000
    snapshot_freq: 5000
    validation_freq: 2000
    num_workers: 32

testing:
    test_times: 1
    test_timesteps: 2
    test_num_diffusion_timesteps: 12

optim:
    decay: 60
    optimizer: "Adam"
    lr: 0.00002
    lr_gamma: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0

# DEQ-specific configuration
deq:
    # General DEQ settings
    enabled: false
    default_iterations: 5
    best_epoch_iterations: 15
    warm_up_epochs: 20
    min_epoch_for_increase: 10
    tolerance: 0.0001
    max_iterations: 15
    
    # Logging and tracking settings
    log_frequency: 100
    track_residuals: false
    save_residual_plots: false
    
    # Component selection for DEQ application
    components:
        middle_layer: true  # Apply DEQ to middle layer in GCNdiff
        final_layer: true   # Apply DEQ to final layer in GCNpose
    
    # Scheduling options
    scheduling:
        type: "fixed"      # "fixed", "linear", "exponential", "cosine"
        start_value: 1
        end_value: 15
    
    # Diffusion integration settings
    diffusion:
        increase_timesteps_for_best: true  # Use more diffusion timesteps for best epoch
        timestep_multiplier: 2             # Multiply timesteps by this factor for best epoch
    
    # Fallback settings
    fallback:
        enabled: true
        replace_nan: true
        max_retries: 3
        
    # Advanced settings
    advanced:
        convergence_metric: "relative"  # "relative" or "absolute"
        anderson_acceleration: false
        damping_factor: 1.0